package com.kopylovis.tossling.core.presentation.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

@Immutable
data class TossyPalette(
    val isDark: Boolean,
    val background: Color,
    val blob1: Color,
    val blob2: Color,
    val blob3: Color,
    val ink: Color,
    val ink2: Color,
    val hairline: Color,
    val glassFill: Color,
    val glassStrong: Color,
    val glassWeak: Color,
    val header: Color,
    val glassStroke: Color,
    val highlightAlpha: Float,
    val glassBlur: Dp,
    val refraction: Float,
    val shadow: Color,
    val shadowRadius: Dp,
    val accent: Color,
    val onAccent: Color,
    val accentInk: Color,
    val accentSoft: Color,
    val danger: Color,
    val onDanger: Color,
    val dangerInk: Color,
    val dangerSoft: Color,
    val success: Color,
    val onSuccess: Color,
    val successInk: Color,
    val island: Color,
    val scrim: Color,
    val track: Color,
    val badge: Color,
    val onBadge: Color,
    val badgeRing: Color,
    val urgentRow: Color,
    val importantSoft: Color,
    val importantInk: Color,
    val codeInline: Color,
    val glassLite: Color,
    val tabContainer: Color,
    val tabIndicator: Color,
) {
    companion object {
        val Light = TossyPalette(
            isDark = false,
            background = Color(0xFFEEF0F5),
            blob1 = Color(0xFFD0CAFD),
            blob2 = Color(0xFFFBCDAA),
            blob3 = Color(0xFFA9DEF0),
            ink = Color(0xFF15171C),
            ink2 = Color(0x9E15171C),
            hairline = Color(0x1415171C),
            glassFill = Color(0x8CFFFFFF),
            glassStrong = Color(0xB3FFFFFF),
            glassWeak = Color(0x66FFFFFF),
            header = Color(0x99F4F5FA),
            glassStroke = Color(0xCCFFFFFF),
            highlightAlpha = 0.6f,
            glassBlur = 24f.dp,
            refraction = 0.35f,
            shadow = Color(0x1428325A),
            shadowRadius = 30f.dp,
            accent = Color(0xFF3067B8),
            onAccent = Color(0xFFFFFFFF),
            accentInk = Color(0xFF1D3F8A),
            accentSoft = Color(0x1A1D3F8A),
            danger = Color(0xFFC53637),
            onDanger = Color(0xFFFFFFFF),
            dangerInk = Color(0xFFA3261B),
            dangerSoft = Color(0x1AC8321E),
            success = Color(0xFF2E9A57),
            onSuccess = Color(0xFFFFFFFF),
            successInk = Color(0xFF1C6B3B),
            island = Color(0xD612141A),
            scrim = Color(0x38141828),
            track = Color(0x1F15171C),
            badge = Color(0xFFD02B31),
            onBadge = Color(0xFFFFFFFF),
            badgeRing = Color(0xE6FFFFFF),
            urgentRow = Color(0x0FC8321E),
            importantSoft = Color(0x24BE7814),
            importantInk = Color(0xFF7A4A00),
            codeInline = Color(0x0D15171C),
            glassLite = Color(0x8CFFFFFF),
            tabContainer = Color.White.copy(alpha = 0.45f),
            tabIndicator = Color.Black.copy(alpha = 0.08f),
        )

        val Dark = TossyPalette(
            isDark = true,
            background = Color(0xFF0E1016),
            blob1 = Color(0xFF3D3368),
            blob2 = Color(0xFF512E1A),
            blob3 = Color(0xFF00415C),
            ink = Color(0xFFF2F3F7),
            ink2 = Color(0xA8F2F3F7),
            hairline = Color(0x1AFFFFFF),
            glassFill = Color(0x802C303E),
            glassStrong = Color(0xA8383C4C),
            glassWeak = Color(0x14FFFFFF),
            header = Color(0x9914161E),
            glassStroke = Color(0x24FFFFFF),
            highlightAlpha = 0.25f,
            glassBlur = 28f.dp,
            refraction = 0.30f,
            shadow = Color(0x59000000),
            shadowRadius = 36f.dp,
            accent = Color(0xFF7AACF6),
            onAccent = Color(0xFF0B1530),
            accentInk = Color(0xFFA0C6FF),
            accentSoft = Color(0x268CAAFF),
            danger = Color(0xFFF2716A),
            onDanger = Color(0xFF2A0805),
            dangerInk = Color(0xFFFF9E96),
            dangerSoft = Color(0x24FF6E5A),
            success = Color(0xFF5CCB88),
            onSuccess = Color(0xFF06210F),
            successInk = Color(0xFF8BE3AE),
            island = Color(0xD1000000),
            scrim = Color(0x66000000),
            track = Color(0x29FFFFFF),
            badge = Color(0xFFF05653),
            onBadge = Color(0xFFFFFFFF),
            badgeRing = Color(0xE6282C3A),
            urgentRow = Color(0x14FF6E5A),
            importantSoft = Color(0x29FFBE5A),
            importantInk = Color(0xFFF8BF6C),
            codeInline = Color(0x47000000),
            glassLite = Color(0x802C303E),
            tabContainer = Color.White.copy(alpha = 0.06f),
            tabIndicator = Color.White.copy(alpha = 0.12f),
        )
    }
}

val ProjectColors: List<Color> = listOf(
    Color(0xFF794DB6),
    Color(0xFF007A7B),
    Color(0xFF9C5313),
    Color(0xFF0076A0),
    Color(0xFF287C42),
    Color(0xFFAD3A55),
)

val LocalTossyPalette = staticCompositionLocalOf { TossyPalette.Light }
